CREATE TABLE USERS (
    USERNAME VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    CREATED_TS TIMESTAMP,
    UPDATED_TS TIMESTAMP,
    DELETED_TS TIMESTAMP,
    ACTIVE BOOLEAN
);